import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, "..");

const inputPath = path.join(rootDir, "src", "tokens", "tokens.json");
const outputDir = path.join(rootDir, "src", "tokens");
const cssOutputPath = path.join(outputDir, "tokens.css");
const scssOutputPath = path.join(outputDir, "_tokens.scss");

function flattenTokens(node, segments = []) {
  if (node && typeof node === "object" && "value" in node) {
    return [{ path: segments, value: node.value }];
  }

  return Object.entries(node).flatMap(([key, value]) =>
    flattenTokens(value, [...segments, key]),
  );
}

function toKebabCase(value) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
}

function toScssName(segments) {
  return [...segments.map(toKebabCase)].join("-");
}

function toCssVarName(segments) {
  return segments.map(toKebabCase).join("-");
}

function buildScssTokenTree(flattenedTokens) {
  const tree = {};

  for (const token of flattenedTokens) {
    let currentNode = tree;

    token.path.forEach((segment, index) => {
      const key = toKebabCase(segment);

      if (index === token.path.length - 1) {
        currentNode[key] = `$${toScssName(token.path)}`;
        return;
      }

      currentNode[key] ??= {};
      currentNode = currentNode[key];
    });
  }

  return tree;
}

function serializeScssMap(node, indent = 0) {
  const padding = "  ".repeat(indent);
  const innerPadding = "  ".repeat(indent + 1);

  if (typeof node === "string") {
    return node;
  }

  const entries = Object.entries(node).map(
    ([key, value]) =>
      `${innerPadding}${toKebabCase(key)}: ${serializeScssMap(value, indent + 1)}`,
  );

  return `(\n${entries.join(",\n")}\n${padding})`;
}

function buildCss(tokens) {
  const lines = [
    "/* This file is generated by scripts/generate-tokens.mjs. */",
    ":root {",
    ...tokens.map(
      ({ path: tokenPath, value }) =>
        `  --${toCssVarName(tokenPath)}: ${value};`,
    ),
    "}",
    "",
  ];

  return lines.join("\n");
}

function buildScss(flattenedTokens) {
  const tokenTree = buildScssTokenTree(flattenedTokens);
  const lines = [
    "// This file is generated by scripts/generate-tokens.mjs.",
    ...flattenedTokens.map(
      ({ path: tokenPath, value }) =>
        `$${toScssName(tokenPath)}: ${value} !default;`,
    ),
    "",
    `$tokens: ${serializeScssMap(tokenTree)} !default;`,
    "",
  ];

  return lines.join("\n");
}

async function main() {
  const raw = await readFile(inputPath, "utf8");
  const flattenedTokens = flattenTokens(JSON.parse(raw));

  await mkdir(outputDir, { recursive: true });
  await writeFile(cssOutputPath, buildCss(flattenedTokens), "utf8");
  await writeFile(scssOutputPath, buildScss(flattenedTokens), "utf8");

  console.log(`Generated ${path.relative(rootDir, cssOutputPath)}`);
  console.log(`Generated ${path.relative(rootDir, scssOutputPath)}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
